# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'todotest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for todotest

  target 'todotestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'todotestUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'RealmSwift'
end
